config/routes.rb
Rails.application.routes.draw do


  root 'home_pages#home'
  
  get   '/help',    to: 'home_pages#help'
  get   '/about',   to: 'home_pages#about'
  get   '/contact', to: 'home_pages#contact'
  get   '/signup',  to: 'users#new'
  get   '/signin',  to: 'sessions#new'
  post  '/signin',  to: 'sessions#create'
  get   '/signout', to: 'sessions#destroy'
  get   '/echart',  to: 'admin#echart'
  get   '/sale',    to: 'admin#sale'

  resources :users do
    resources :addresses   
  end

  resources :stores

  resources :products do
    resources :comments
    resources :carts, only: [:create, :destroy, :new]
  end

  resources :orders do
    resources :order_items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :order_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  belongs_to :store
  validates :store_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :user_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_one :store, dependent: :destroy

    has_many :carts, dependent: :destroy
    has_many :orders, dependent: :destroy  
    has_many :comments, dependent: :destroy
    has_many :addresses, dependent: :destroy
    
    attr_accessor :remember_token
    
    before_save {email.downcase!}
    validates :name, presence: true, length: {maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:255}, 
                      format: {with: VALID_EMAIL_REGEX}, 
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length:{minimum:6}, allow_nil: true

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_action :signed_in_user, only: [:order, :echart]
  before_action :admin_user, only: [:order, :echart]

  def echart
      items = OrderItem.all
      @data = Hash.new
      items.each do |item|
          type = item.product.category.to_s
          if @data.include?(type)
              @data[type] += 1
          else
              @data[type] = 1
          end
      end
  end

  def sale
      @orders = Order.all
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      flash[:success] = "Comment Added"
      redirect_to @product
    else
      render 'new'
    end

  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    product = @comment.product
    @comment.destroy
    flash[:success] = "Comment Destroyed"
    redirect_to product
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:product_id, :content)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = 'Turquoise'
        if page_title.empty?
            base_title
        else
            page_title + '|' + base_title
        end
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: session[:user_id])
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                sign_in user
                @current_user = user
            end
        end
    end

    def current_user?(user)
        user == current_user
    end

    def signed_in?
        !current_user.nil?
    end

    def has_store?
        !current_user.store.nil?
    end

    def sign_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end

    def signed_in_user
        unless signed_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to signin_url
        end
    end
  
  
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
    <%#= link_to gravatar_for(store.user, size: 50), store.user %>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"> <%= link_to comment.user.name, comment.user%> </h3>
    </div>

    <div class="panel-body">
    <span class="content"> <%= comment.content%> </span>
    <span class="timestamp">
        Added <%= time_ago_in_words(comment.created_at) %> ago.
    </span>
    
    </div>
</div>
    <% if comment.user == current_user %>
    <%= link_to "Remove", product_comment_path(@product, comment), class:"btn btn-danger",
        method: :delete, data: { confirm: 'Are you sure?' }%>
    <% end %>
</li>

app/views/comments/_form.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= form_for(@comment, url:product_comments_path) do |form|%>
      <%= render 'shared/error_messages', object: @comment%>
  
      <%= form.label :content %>
      <%= form.text_area :content, class: 'form-control'%>
 
      <%= form.submit 'Add Comment', class: 'btn btn-primary'%>
      <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.product %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', @comment.product %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @comment.product %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>