config/routes.rb
Rails.application.routes.draw do


  root 'home_pages#home'
  
  get   '/help',    to: 'home_pages#help'
  get   '/about',   to: 'home_pages#about'
  get   '/contact', to: 'home_pages#contact'
  get   '/signup',  to: 'users#new'
  get   '/signin',  to: 'sessions#new'
  post  '/signin',  to: 'sessions#create'
  get   '/signout', to: 'sessions#destroy'
  get   '/echart',  to: 'admin#echart'
  get   '/sale',    to: 'admin#sale'

  resources :users do
    resources :addresses   
  end

  resources :stores

  resources :products do
    resources :comments
    resources :carts, only: [:create, :destroy, :new]
  end

  resources :orders do
    resources :order_items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :order_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  belongs_to :store
  validates :store_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :user_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_one :store, dependent: :destroy

    has_many :carts, dependent: :destroy
    has_many :orders, dependent: :destroy  
    has_many :comments, dependent: :destroy
    has_many :addresses, dependent: :destroy
    
    attr_accessor :remember_token
    
    before_save {email.downcase!}
    validates :name, presence: true, length: {maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:255}, 
                      format: {with: VALID_EMAIL_REGEX}, 
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length:{minimum:6}, allow_nil: true

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_action :signed_in_user, only: [:order, :echart]
  before_action :admin_user, only: [:order, :echart]

  def echart
      items = OrderItem.all
      @data = Hash.new
      items.each do |item|
          type = item.product.category.to_s
          if @data.include?(type)
              @data[type] += 1
          else
              @data[type] = 1
          end
      end
  end

  def sale
      @orders = Order.all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create  
    @cart = current_user.carts.build(cart_params)
    @product = Product.find(params[:product_id])
    @cart.product = @product
    @cart.original_price = @cart.product.price

    if @cart.save
        flash[:success] = "Product"
        redirect_to products_path
    else
        render root_url
    end

    #respond_to do |format|
    #  if @cart.save
    #    format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
    #    format.json { render :show, status: :created, location: @cart }
    #  else
    #    format.html { render :new }
    #    format.json { render json: @cart.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    flash[:success] = "cart deleted"
    redirect_to current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:num)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = 'Turquoise'
        if page_title.empty?
            base_title
        else
            page_title + '|' + base_title
        end
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: session[:user_id])
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                sign_in user
                @current_user = user
            end
        end
    end

    def current_user?(user)
        user == current_user
    end

    def signed_in?
        !current_user.nil?
    end

    def has_store?
        !current_user.store.nil?
    end

    def sign_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end

    def signed_in_user
        unless signed_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to signin_url
        end
    end
  
  
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/carts/_cart.html.erb
<li id="cart-<%= cart.id %>">
    <%#= link_to gravatar_for(store.user, size: 50), store.user %>

<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"> <%= link_to cart.product.name, cart.product%> </h3>
    </div>

    <div class="panel-body">
    <span class="content"> num: <%= cart.num%> </span>
    <span class="content"> 
        <% if cart.original_price > cart.product.price%> 
        <span class="label label-success"><%= cart.original_price - cart.product.price%> off </span>
        <%end%>
    </span>
    <span class="timestamp">
        Added <%= time_ago_in_words(cart.created_at) %> ago.
    </span>
    
    </div>
</div>
    <%= link_to "Remove", product_cart_path(cart), class:"btn btn-danger",
        method: :delete, data: { confirm: 'Are you sure?' }%>
    
</li>

app/views/carts/_form.html.erb
<div class = "row">
  <div class = "col-md-6 col-md-offset-3">
    <%= form_for(@cart, url:product_carts_path) do |form|%>
      <%= render 'shared/error_messages', object: @cart%>
  
      <%= form.label :num %>
      <%= form.number_field :num, class: 'form-control'%>
 
      <%= form.submit 'I want to buy it', class: 'btn btn-primary'%>
      <% end %>
  </div>
</div>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', user_carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product</th>
      <th>Num</th>
      <th>Original price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.user %></td>
        <td><%= cart.product %></td>
        <td><%= cart.num %></td>
        <td><%= cart.original_price %></td>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_user_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_user_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @cart.user %>
</p>

<p>
  <strong>Product:</strong>
  <%= @cart.product %>
</p>

<p>
  <strong>Num:</strong>
  <%= @cart.num %>
</p>

<p>
  <strong>Original price:</strong>
  <%= @cart.original_price %>
</p>

<%= link_to 'Edit', edit_user_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>