config/routes.rb
Rails.application.routes.draw do


  root 'home_pages#home'
  
  get   '/help',    to: 'home_pages#help'
  get   '/about',   to: 'home_pages#about'
  get   '/contact', to: 'home_pages#contact'
  get   '/signup',  to: 'users#new'
  get   '/signin',  to: 'sessions#new'
  post  '/signin',  to: 'sessions#create'
  get   '/signout', to: 'sessions#destroy'
  get   '/echart',  to: 'admin#echart'
  get   '/sale',    to: 'admin#sale'

  resources :users do
    resources :addresses   
  end

  resources :stores

  resources :products do
    resources :comments
    resources :carts, only: [:create, :destroy, :new]
  end

  resources :orders do
    resources :order_items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :order_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  belongs_to :store
  validates :store_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :user_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_one :store, dependent: :destroy

    has_many :carts, dependent: :destroy
    has_many :orders, dependent: :destroy  
    has_many :comments, dependent: :destroy
    has_many :addresses, dependent: :destroy
    
    attr_accessor :remember_token
    
    before_save {email.downcase!}
    validates :name, presence: true, length: {maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:255}, 
                      format: {with: VALID_EMAIL_REGEX}, 
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length:{minimum:6}, allow_nil: true

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_action :signed_in_user, only: [:order, :echart]
  before_action :admin_user, only: [:order, :echart]

  def echart
      items = OrderItem.all
      @data = Hash.new
      items.each do |item|
          type = item.product.category.to_s
          if @data.include?(type)
              @data[type] += 1
          else
              @data[type] = 1
          end
      end
  end

  def sale
      @orders = Order.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authority_check, only: [:edit, :new, :create, :update, :destroy]


  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comments = @product.comments.paginate(page: params[:page])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.store.products.create(product_params)
    if @product.save
      flash[:success] = 'Add new product Successfully'
    else
      flash[:danger] = 'Can not Add product'
    end
    redirect_to current_user.store
   
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :category, :info, :price)
    end

    def authority_check
      signed_in_user
      if !has_store?
        flash[:danger] = "Please create your store"
        redirect_to new_store_url(current_user)
      end
    end
  
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = 'Turquoise'
        if page_title.empty?
            base_title
        else
            page_title + '|' + base_title
        end
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: session[:user_id])
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                sign_in user
                @current_user = user
            end
        end
    end

    def current_user?(user)
        user == current_user
    end

    def signed_in?
        !current_user.nil?
    end

    def has_store?
        !current_user.store.nil?
    end

    def sign_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end

    def signed_in_user
        unless signed_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to signin_url
        end
    end
  
  
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/products/_form.html.erb
<div class = "row">
    <div class = "col-md-6 col-md-offset-3">
        <%= form_for(@product) do |f|%>
            <%= render 'shared/error_messages', object: @product %>
    
        <%= f.label :name%>
        <%= f.text_field :name, class: 'form-control'%>

        <%= f.label :category%>
        <%= f.text_field :category, class: 'form-control'%>

        <%= f.label :info%>
        <%= f.text_field :info, class: 'form-control'%>

        <%= f.label :price, "Price"%>
        <%= f.number_field :price, class: 'form-control'%>
        
        <%= f.submit yield(:btn_text), class:"btn btn-primary"%>
        <%end%>
    </div>
</div>

app/views/products/_product.html.erb
<li id="product-<%= product.id %>">
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"> <%= link_to product.name, product%> 
            <span class="label label-info"> <%= product.category %></span>
        </h3>
        
    </div>
    <div class="panel-body">

    <span class="content"> <small><p> <%= product.info %> </p></small> </span>

    <span class="content"> <strong>Price: <%= product.price%> </strong> </span>
    <div class="panel-footer">
        <span class="timestamp">
        Added <%= time_ago_in_words(product.created_at) %> ago.
        </span>
    </div>
    
    </div>
</div>
</li>

app/views/products/edit.html.erb
<%provide(:btn_text, 'Change It')%>
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% provide(:title, 'Products')%>
<h1>All products</h1>

<%= will_paginate %>

<ul class="users">
    <%= render @products %>
</ul>

<%= will_paginate %>

app/views/products/new.html.erb
<%provide(:btn_text, 'Add new product')%>
<h1>New Product</h1>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<% provide(:title, @product.name)%>
<p id="notice"><%= notice %></p>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <p>
        <strong>Name:</strong>
        <%= @product.name %>
      </p>

      <p>
        <strong>category:</strong>
        <%= @product.category %>
      </p>

      <p>
        <strong>Info:</strong>
        <%= @product.info %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= @product.price %>
      </p>
      
      <span class="content">
        <%= link_to 'Goto Store', @product.store , class:"btn btn-warning btn-block"%>
      </span>

      <span class="content">
        <%= link_to 'Add comment', new_product_comment_path(@product), class:"btn btn-primary btn-block"%>
      </span>
      <span class="content">
        <%= link_to 'Add to cart',new_product_cart_path(@product), class:"btn btn-success btn-block"%>
      </span>
      <% if current_user.store == @product.store %>
      <span class="content">
        <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-info btn-block" %>
      </span>
      <% end %>

    </section>
  </aside>
  <div class="col-md-8">
    <% if @product.comments.any? %>
    <h3>Comments </h3>
      <ol class="products">
        <%= render @comments %>
      </ol>
    <%= will_paginate @comments %>
    <% end %>
  </div>
</div>