config/routes.rb
Rails.application.routes.draw do


  root 'home_pages#home'
  
  get   '/help',    to: 'home_pages#help'
  get   '/about',   to: 'home_pages#about'
  get   '/contact', to: 'home_pages#contact'
  get   '/signup',  to: 'users#new'
  get   '/signin',  to: 'sessions#new'
  post  '/signin',  to: 'sessions#create'
  get   '/signout', to: 'sessions#destroy'
  get   '/echart',  to: 'admin#echart'
  get   '/sale',    to: 'admin#sale'

  resources :users do
    resources :addresses   
  end

  resources :stores

  resources :products do
    resources :comments
    resources :carts, only: [:create, :destroy, :new]
  end

  resources :orders do
    resources :order_items
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  validates :user_id, presence: true
  validates :product_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  validates :order_id, presence: true
  validates :product_id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  belongs_to :store
  validates :store_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
  validates :user_id, presence: true
  validates :info, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
    has_one :store, dependent: :destroy

    has_many :carts, dependent: :destroy
    has_many :orders, dependent: :destroy  
    has_many :comments, dependent: :destroy
    has_many :addresses, dependent: :destroy
    
    attr_accessor :remember_token
    
    before_save {email.downcase!}
    validates :name, presence: true, length: {maximum:50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum:255}, 
                      format: {with: VALID_EMAIL_REGEX}, 
                      uniqueness: {case_sensitive: false}
    has_secure_password
    validates :password, presence: true, length:{minimum:6}, allow_nil: true

    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = 'Turquoise'
        if page_title.empty?
            base_title
        else
            page_title + '|' + base_title
        end
    end
    
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
        session[:user_id] = user.id
    end

    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: session[:user_id])
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                sign_in user
                @current_user = user
            end
        end
    end

    def current_user?(user)
        user == current_user
    end

    def signed_in?
        !current_user.nil?
    end

    def has_store?
        !current_user.store.nil?
    end

    def sign_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end

    def signed_in_user
        unless signed_in?
          store_location
          flash[:danger] = "Please log in."
          redirect_to signin_url
        end
    end
  
  
    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/admin/echart.html.erb
<div id="main" style="width: 600px;height:400px;"></div>
  <script src="https://echarts.baidu.com/dist/echarts.min.js"></script>
  <script>
    var myChart = echarts.init(document.getElementById('main'));
    var option = {
      title: {
        text: 'Category'
      },
      tooltip: {},
      legend: {
        data: ['销量']
      },
      xAxis: {
        data: <%= raw @data.keys %>
      },
      yAxis: {},
      series: [{
        name: '销量',
        type: 'bar',
        itemStyle: {
          normal: {
            color: function(params) {
              var colorList = [
                '#C1232B','#B5C334','#FCCE10','#E87C25','#27727B',
                '#FE8463','#9BCA63','#FAD860','#F3A43B','#60C0DD',
                '#D7504B','#C6E579','#F4E001','#F0805A','#26C0C0'];
              return colorList[params.dataIndex]
            },
            label: {
              show: true,
              position: 'top',
              formatter: '{b}\n{c}'
            }
          }
        },
　　　　　barWidth:70,
        data: <%= @data.values %>
      }]
    };
    myChart.setOption(option);
</script>

app/views/admin/sale.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class='table'>
  <thead>
    <tr>
      <th>Id</th>
      <th>Address</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= link_to "#{order.id}", order %></td>
        <td><%= order.address %></td>
        <td>
          <% if order.status == 0%>
            <span class="label label-info"> Processing </span>
          <% else %>
            <span class="label label-success"> Finish </span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Copyright nzy &copy; 2019
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path%></li>
            <li><%= link_to "Contact", contact_path%></li>
        <ul>
    </nav>
<footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Turquoise", root_path, id:"logo"%>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <% if signed_in?%>
                    <li><%= link_to "Users", users_path %></li>
                    <li><%= link_to "Cart", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <% if has_store? %>
                        <li><%= link_to "My store", store_path(current_user.store) %>                       
                    <% else %>
                        <li><%= link_to "New store", new_store_path%><li>
                    <% end %>
                    <li><%= link_to "Sign out", signout_path %></li>
                <% else %>
                    <li><%= link_to "Home", root_path %></li>
                    <li><%= link_to "Help", help_path %></li>
                    <li><%= link_to "Sign in", signin_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
      <title> <%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <div class="container">
      <% flash.each do |message_type, message|%>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
    <div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <div class = "alert alert-danger">
            The form contains <%= pluralize(object.errors.count, "error")%>.
        </div>
        <ul>
            <% object.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>